parser: babel-eslint
extends:
  - airbnb-base
rules:
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - "**/__tests__/*.js"
  max-len:
    - error
    - code: 120
      ignoreComments: true
  semi:
    - error
    - never
env:
  browser: true
  es6: true
  jasmine: true
  jest: true
